"""creo modelo offer

Revision ID: 00ca8ecfcd84
Revises: be64dade5296
Create Date: 2024-10-18 23:16:12.158721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ca8ecfcd84'
down_revision = 'be64dade5296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('min_purchase_amount', sa.Float(), nullable=False),
    sa.Column('offer_type', sa.String(length=50), nullable=False),
    sa.Column('applicable_to_product_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicable_to_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    # ### end Alembic commands ###
