"""agrego modelo banner

Revision ID: decd9a905160
Revises: 00ca8ecfcd84
Create Date: 2024-10-22 23:18:57.442271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decd9a905160'
down_revision = '00ca8ecfcd84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_offer', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
